[package]
name = "muon_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.20.3"
quote = "1.0.35"
syn = "2.0.48"
venial = "0.5.0"
proc-macro2 = "1.0.76"
